//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travhotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int menu_id { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public int restaurant_id { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
