//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travhotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int room_id { get; set; }
        public string room_type { get; set; }
        public string status { get; set; }
        public int room_price { get; set; }
        public int hotel_id { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
