//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travhotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traveler
    {
        public int traveler_id { get; set; }
        public string traveler_name { get; set; }
        public string traveler_email { get; set; }
        public string traveler_password { get; set; }
        public string traveler_contact { get; set; }
    }
}
